# Generated by Django 2.2.8 on 2020-01-22 10:37

from django.db import migrations
from django.contrib.auth.models import User
from DjangoBlog.settings import SITE_DOMAIN_NAME, SITE_ID, DJANGO_SU_NAME, DJANGO_SU_EMAIL, DJANGO_SU_PASSWORD


def update_site_name(apps, schema_editor):
    SiteModel = apps.get_model('sites', 'Site')

    SiteModel.objects.update_or_create(
        pk=SITE_ID,
        defaults={
            "domain": SITE_DOMAIN_NAME,
            "name": SITE_DOMAIN_NAME
        }
    )


def generate_superuser(apps, schema_editor):

    superuser = User.objects.create_superuser(
        username=DJANGO_SU_NAME,
        email=DJANGO_SU_EMAIL,
        password=DJANGO_SU_PASSWORD)
    superuser.save()


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(update_site_name),
        migrations.RunPython(generate_superuser),
    ]
